name: levels_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
      - asset: assets/fonts/MontserratBlack.ttf
      - asset: assets/fonts/MontserratBold.ttf
      - asset: assets/fonts/MontserratSemiBold.ttf
      - asset: assets/fonts/MontserratRegular.ttf
      - asset: assets/fonts/MontserratLight.ttf
